### PR TITLE
Refresh rosgraph when params checkbox is clicked

### PR DESCRIPTION
**Pull request by Yadunund**
Fix behavior reported here https://github.com/osrf/ros2_test_cases/issues/1016#issuecomment-1533433426

### CODE REVIEW

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18680/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13206/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19418/)

**Comment by clalancette** [comment]
We'll also need to backport this to Iron.

**Comment by Yadunund** [comment]
Windows failure seems unrelated 🤔

**Comment by clalancette** [comment]
> Windows failure seems unrelated thinking

Yeah, that was infrastructure.  I re-ran it and it looks good now.

**Comment by clalancette** [comment]
@Mergifyio backport iron

**Pull request merged**
