### PR TITLE
Fix typo that caused a crash when trying to load a dot file.

### PR DESCRIPTION
**Pull request by JWhitleyAStuff**
Bug was seen on Melodic - tested as fixed on Melodic.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thanks for the fix.

**Comment by dirk-thomas** [comment]
Cherry-picked to the `crystal` branch: b4e479bc3f7c41ab86e94e828f0e3409f30d7ffb.

**Comment by moriarty** [comment]
@dirk-thomas it looks like rqt_plot hasn’t been released to melodic with this change.

Could you bloom it?

PS: no rush- Frohe Weihnachten ;)

**Comment by dirk-thomas** [comment]
Sure, done: ros/rosdistro#23416.

**Pull request merged**
