### PR TITLE
Add setup.cfg with script install directories

### PR DESCRIPTION
**Pull request by ahcorde**
Fixed package to run with `ros2 run rqt_graph rqt_graph`. Related to this issue https://github.com/ros-visualization/rqt_console/issues/20

### CODE REVIEW

**Comment by ivanpauno** [comment]
> This doesn't look right. This is a CMake package so it doesn't use the added `setup.cfg` file at all.

It seems to me that it's an `ament_python` package:

https://github.com/ros-visualization/rqt_graph/blob/22952ef7604ed76f573cfae896c96c435203339a/package.xml#L29


Maybe you were checking `master` branch instead of `crystal-devel`?

**Comment by dirk-thomas** [comment]
> Maybe you were checking `master` branch instead of `crystal-devel`?

I indeed did. Please ignore my comment.

**Comment by ahcorde** [comment]
Running CI up to `rqt_graph`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10909/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6261/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8884/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10802/)

**Comment by dirk-thomas** [comment]
With this change you can't invoke `rqt_graph` anymore (without `ros2 run`) so this breaks existing use cases and documentation.

**Comment by jacobperron** [comment]
> With this change you can't invoke rqt_graph anymore (without ros2 run) so this breaks existing use cases and documentation.

I hadn't considered this case. I think we should make a patch to re-enable this functionality before releasing (or revert this change).

**Comment by jacobperron** [comment]
Doing something similar to [`rqt_gui`](https://github.com/ros-visualization/rqt/tree/crystal-devel/rqt_gui) might work; adding an explicit executable to bin and installing it as a data file: https://github.com/ros-visualization/rqt/blob/b198efc2b1d4433f13442410e3a12ae5c4a1106b/rqt_gui/setup.py#L18

**Comment by jacobperron** [comment]
> With this change you can't invoke rqt_graph anymore (without ros2 run) so this breaks existing use cases and documentation.

See https://github.com/ros-visualization/rqt_graph/pull/49 for a fix.

**Pull request merged**
