### PR TITLE
graph load/save into DOT file corrections for py3

### PR DESCRIPTION
**Pull request by skudryas**
Just a small corrections for save / load .DOT files

### CODE REVIEW

**Comment by russkel** [comment]
Fixes #67 presumably.

**Comment by iwatake2222** [comment]
The problem still happens with galactic. It would be great if this PR is merged to other branches.

**Comment by wjwwood** [comment]
@mergifyio backport ros2 humble-devel galactic-devel

**Comment by clalancette** [comment]
> I guess mergify isn't set up on this organization.

I'll enable it.

**Comment by wjwwood** [comment]
@Mergifyio backport ros2 humble-devel galactic-devel

**Comment by iwatake2222** [comment]
Thank you !!

**Pull request merged**
